/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_equalizer_mimo.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c98e5f90c5dcbf285fc5a9850760a79a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/frame_equalizer_mimo.h>
// pydoc.h is automatically generated in the build directory
#include <frame_equalizer_mimo_pydoc.h>

void bind_frame_equalizer_mimo(py::module& m)
{

    using frame_equalizer_mimo    = ::gr::ieee802_11::frame_equalizer_mimo;


    py::class_<frame_equalizer_mimo, gr::block, gr::basic_block,
        std::shared_ptr<frame_equalizer_mimo>>(m, "frame_equalizer_mimo", D(frame_equalizer_mimo))

        .def(py::init(&frame_equalizer_mimo::make),
           py::arg("algo"),
           py::arg("freq"),
           py::arg("bw"),
           py::arg("log"),
           py::arg("debug"),
           D(frame_equalizer_mimo,make)
        )
        




        
        .def("set_algorithm",&frame_equalizer_mimo::set_algorithm,       
            py::arg("algo"),
            D(frame_equalizer_mimo,set_algorithm)
        )


        
        .def("set_bandwidth",&frame_equalizer_mimo::set_bandwidth,       
            py::arg("bw"),
            D(frame_equalizer_mimo,set_bandwidth)
        )


        
        .def("set_frequency",&frame_equalizer_mimo::set_frequency,       
            py::arg("freq"),
            D(frame_equalizer_mimo,set_frequency)
        )

        ;




}








