/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

 /***********************************************************************************/
 /* This file is automatically generated using bindtool and can be manually edited  */
 /* The following lines can be configured to regenerate this file during cmake      */
 /* If manual edits are made, the following tags should be modified accordingly.    */
 /* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
 /* BINDTOOL_USE_PYGCCXML(0)                                                        */
 /* BINDTOOL_HEADER_FILE(sync_long_extra.h)                                         */
 /* BINDTOOL_HEADER_FILE_HASH(00000000000000000000000000000000)                     */
 /***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/sync_long_extra.h>
// pydoc.h is automatically generated in the build directory
#include <sync_long_extra_pydoc.h>

void bind_sync_long_extra(py::module& m)
{
    using sync_long_extra = ::gr::ieee802_11::sync_long_extra;

    py::class_<sync_long_extra, gr::block, gr::basic_block,
        std::shared_ptr<sync_long_extra>>(m, "sync_long_extra", D(sync_long_extra))

        .def(py::init(&sync_long_extra::make),
            py::arg("sync_length"),
            py::arg("log") = false,
            py::arg("debug") = false,
            D(sync_long_extra, make)
        )

        ;
}